// school -> work
export const expDetails = [
  {
    id: 1,
    title: "High School Education",
    company_name: "D.A.V. Public School, Ranchi, Jharkhand",
    date: "2019",
    points: ["Class XII: 85.20%", "Class X: 10CGPA"],
    type: "school",
  },
  {
    id: 2,
    title: "Bachelor of Engineering in Information Science",
    company_name: "RNS Institute of Technology, Bengalore, Karnataka",
    date: "Aug 2019 - May 2023",
    points: ["Overall CGPA: 8.66"],
    type: "school",
  },
  {
    id: 3,
    title: "Full-Stack Developer Intern",
    company_name: "Startupshive",
    date: "Oct 2022 - Jan 2023",
    points: [
      "Designed and implemented optimized and scalable data schemas reduced data storage costs by 15% while improving data retrieval efficiency by 30%",
      "Enhanced backend APIs using C# ASP.NET and achieved 20% performance boost, reducing response times to 50 ms.",
    ],
    type: "work",
  },
  {
    id: 4,
    title: "Software Development Engineer Intern",
    company_name: "HashedIn by Deloitte",
    date: "Mar 2023 - Jun 2023",
    points: [
      "Completed a comprehensive 12-week boot-camp training program focused on Backend Development with NestJS & NodeJS, Frontend Development with NextJS & TypeScript, and Android Development using Flutter.",
      "Engineered a proctoring tool to monitor candidates during hiring test.",
      "Implemented advanced features including real-time eye movement tracking, multiple person detection, and object detection like mobile phones using Tensorflow.js along with browser lockdown mechanism for enhanced security.",
      "Developed robust backend APIs with NodeJs and Express, integrating WebRTC and Socket.io for real-time video streaming.",
      "Collaborated with multiple teams to ensure successful deployment and facilitate cross-functional functionalities.",
      "Led a team of 4 members, overseeing project development, coordinating tasks, and ensuring project success and achieved runner-up position in HashedIn by Deloitte's product month.",
    ],
    type: "work",
  },
  {
    id: 5,
    title: "Full-Stack Developer Intern",
    company_name: "ChatGPT Writer",
    date: "Aug 2023 - Sep 2023",
    points: [
      "Successfully migrated the APIs from serverless runtime to edge runtime, resulting in an impressive 30% reduction in response time, enhancing user satisfaction.",
      "Integrated real-time streaming in generated responses, increasing user engagement and reducing wait times by 50%.",
      "Leveraged Notion as CMS to create blogging pages, simultaneously implementing Incremental Static Regeneration reducing resource consumption, and slashing page load times by 40%, enhancing website responsiveness.",
    ],
    type: "work",
  },
  {
    id: 6,
    title: "Software Developer Intern",
    company_name: "Right Prompt Technologies",
    date: "Oct 2023 - Dec 2023",
    points: [
      "Developed a Proof of Concept (POC), connecting banks directly with customers (B2C), streamlining the user journey and improving service accessibility.",
      "Integrated and customized ServiceNow to enhance operational workflows, improving efficiency and service delivery for clients.",
      "Worked with ServiceNow components, including Scheduled Jobs, Script Includes, UI Policies, UI Actions, and Business Rules, to automate processes and optimize the user experience.",
    ],
    type: "work",
  },
  {
    id: 7,
    title: "Software Developer Engineer",
    company_name: "HashedIn by Deloitte",
    date: "Jan 2024 - Present",
    points: [
      "Gained cross-industry expertise by contributing to projects across pharmaceutical, finance, and retail domains.",
      "Worked on the development of a scalable content generation platform using ReactJS and Django, focusing on performance, maintainability, and extensibility.",
      "Strengthened application security by introducing fine-grained role-based access control (RBAC) and user permissions management.",
      "Revamped performance architecture, improving the app’s Lighthouse score from 55 to 85+ through strategic code-splitting, resource minification, lazy loading, and advanced caching — resulting in a 30% smaller bundle size.",
      "Utilized state management libraries like Zustand and Redux to efficiently manage complex application states, ensuring seamless data flow.",
      "Enhanced test infrastructure with Vitest, achieving 85%+ code coverage and significantly lowering defect rates during QA cycles by 15-20%.",
      "Utilized UI frameworks like Material-UI, Ant Design and other custom design libraries to deliver sleek, responsive, and accessible components tailored for enterprise users.",
      "Crafted performant GraphQL operations and seamlessly integrated them with Django-based APIs, improving response consistency and reducing latency.",
      "Actively mentored freshers and also contributed to regular code reviews, promoting best practices and continuous codebase quality improvements.",
    ],
    type: "work",
  },
];
